### ISSUE TITLE
Make Android-App available on F-Droid

### ISSUE THREAD

**Issue by natrius** [The1only/rosettadrone#104]
I'm thinking about buying an DJI Maveric Mini 2 and looking for OSS Software to use with. Through https://forum.dji.com/thread-142292-1-1.html and https://discuss.ardupilot.org/t/dji-phantom-4-pro-v2-0-and-mission-planner/35584/9 i finally found https://github.com/diux-dev/rosettadrone that seemed abandoned and after clicking through every fork manually and checking the history i finally found https://github.com/The1only/rosettadrone_old and this one. 

There is no release-page here but i guess its still an an android app as well, so maybe make it available on F-Droid https://f-droid.org/? I guess a good resource is https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests this or more can be found here https://f-droid.org/en/docs/FAQ_-_App_Developers/ 

If this app does not meet the criteria, it may be possible to contact @IzzySoft with his repo https://apt.izzysoft.de/fdroid/index/info if this maybe be a way. 

Sidenote: It might be beneficial to post on these two forums so more people get drawn here and more help may be available?

**Comment by lmore377** [comment]
I think the main issue with having a prebuilt version of the app is that there's no one willing to share their DJI / Google Maps API keys. I'm not sure about DJI but I know that the maps API can get pricey pretty quickly if it's used for anything other than personal use. Plus I'm pretty sure the DJI and Maps SDK aren't open source so that makes it ineligible for F-Droid.

**Comment by natrius** [comment]
Ah, i see. Is google needed? Wouldn't it be possible to use OSM for that? Or is it oligatory to use google-stuff when using a DJI drone? 

An alternative would be creating your own f-droid-repo so anybody who is interested could add this repo to his f-droid and receive updates through there. See https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/ for example. In this case there is no need to open source everything.

**Comment by kripper** [comment]
Won't fix in the short term. We are targeting developers, not final users.
