### ISSUE TITLE
Disconnection when Reconnecting Smart RC

### ISSUE THREAD

**Issue by gab933** [The1only/rosettadrone#105]
Hi,
I made the following test:
* Start application with Internet connection on (everything works as expected)
* Disconnect Smart RC from Wi-fi (emulating Internet disconnection)
* Connect Smart RC to Wi-fi again (all ops have been performed with app still running)

I noticed telemetry is not anymore received on my GCS.
Instead, commands from GCS are correctly sent to Rosetta, but drone does not execute them.
I attach a log example.
At 10:06:00 I disconnected Wi-fi, and an error appears:
"set_timerslack_ns write failed"
.
.
At 10:06:32 I connect again Wi-fi and same error as before appers, together with:
"org.json.jsonexception"
.
.

How can I fix this issue, in such a way I'm able to manage disconnection?
Thank you

![Screenshot (71)](https://user-images.githubusercontent.com/71692066/155291461-7369910d-fb95-453e-92f1-e2e86b95daf0.png)

**Comment by The1only** [comment]
I have seen this too. Maybe it’s time to fix it.
I belive it is something about the order of UDP connections, maybe there is an error we are overlooking, a missing retry?

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by gab933** [comment]
Thank you.
I'm attempting to solving the issue but I'm not able to understand which callback/service manages the internet/wifi connection.
Anyway I was able to manage the drone disconnection while app is running. In this way, it is possible to disconnect and reconnect drone (e.g., for changing battery) without restarting the app. If you are agree I can make a pull request on it.
Best Regards,

Gabriele

**Comment by kripper** [comment]
Please check latest version.
