### ISSUE TITLE
 I still can't solve Linking C shared library libdjivideojni.so FAILED: libdjivideojni.so

### ISSUE THREAD

**Issue by Yyang212** [The1only/rosettadrone#106]
Sorry, I still can't solve Linking C shared library libdjivideojni.so FAILED: libdjivideojni.so, and I have cloned rosettadrone via git lfs, I am a newbie, could you please give me a more detailed tutorial, thanks

**Comment by Yyang212** [comment]
Oh, I solved it!!!

**Comment by dkapur17** [comment]
> Oh, I solved it!!!

Hey could you let me know how you solved this issue? Thanks.

**Comment by Yyang212** [comment]
> 
I seem to remember that I solved it by git this project to the desktop and open it in the Android Studio.

**Comment by The1only** [comment]
You got to install git long files support...
