### ISSUE TITLE
Video Streaming from Mavic Air 2 to QGC

### ISSUE THREAD

**Issue by karikolehmainen** [The1only/rosettadrone#108]
I have Mavic Air 2 which I would like to connect to QGC. Connection works in terms of telemetry and so on. Video receiving didn't work from out of the box but I got it working by modifying switch statement in validateTranscodingMethod -method at MainActivity with definition for MAVIC_AIR_2 like so: 
case MAVIC_AIR_2:
                return true;

Video transmission to QGC however is still not working. I have setup the encoding to h.264 in video settings (not sure if that applies to video sending) and in settings I have enabled video feed and  set port to 5600. In QGC I have set video application settings to UDP h.264 at port 5600 and fileformat to mp4 (set to mp4 in Rosetta as well). It is still not working. 

So my question is that is there some other modifications needed for video streaming from Rosetta to QGC work or am I missing some settings? It is bit difficult to debug as the debug logs to Android studio would require USB connection but drone requires that as well...

**Comment by jess-sys** [comment]
UP!

**Comment by kripper** [comment]
Check https://github.com/The1only/rosettadrone/issues/111#issuecomment-1249275135
