### ISSUE TITLE
Waypoint Action like START_TAKE_PHOTO not working

### ISSUE THREAD

**Issue by ghost** [The1only/rosettadrone#109]
When developing missions with Waypoint Actions like START_TAKE_PHOTO, START_RECORD, STOP_RECORD I have observed that this works only with the last waypoint. The actions are not executed in the intermediate waypoints.

How can we add different waypoint actions? Has anyone developed a solution for this?

Thank You

Himanshu V
Vyorius Drones
New Delhi, India

**Comment by The1only** [comment]
A new version is out, it introduces a loot of new things, so I branched the 1.14.x that we have used for the last year, just in case.
The new 1.16.1 should handle mission and waypoints better. 
Stuff like on-the-fly donwnload and mail repost og images is now supported, and work while still flying.

**Comment by Phillweston** [comment]
I noticed that the last time the commit updated the live FTP image download function, but at present, the use of this function is not written in both README and wiki. So let me ask, if I want to take a photo in a waypoint mission, and export the photo to the QGroundControl end after the waypoint mission, how should I do it? Thank you

**Comment by Phillweston** [comment]
# When using waypoint actions like taking photos in waypoint, an error occurs after uploading the mission plan:

## APP
![N4~UT UZJX{ T3M~HP0P3PL](https://user-images.githubusercontent.com/42629755/172671976-988edc7f-73f1-46b3-8223-54609cbcf0ad.png)

## QGC
![L1NFX5$)}GY~JA(X9X(T1 B](https://user-images.githubusercontent.com/42629755/172672055-824927bf-be56-4265-9189-205ab09d91c3.png)

**Comment by kripper** [comment]
Can be easily implemented in new MissionManager class. Do you still need it?
What exactly do you want?

a) Desired elapsed time between two consecutive pictures (in seconds). Minimum values depend on hardware (typically greater than 2 seconds)?
b) A total number of images to capture?

**Comment by kripper** [comment]
Closing for now.
