### ISSUE TITLE
Rosetta drone 2 in M300

### ISSUE THREAD

**Issue by druzzo** [The1only/rosettadrone#111]
Hi!

I tested Rosetta drone 2 in an M300 using a Smart Controller.

I was able to load Rosetta Drone 2 (v5.2) in the Smart Controller using Android Studio. It works and it seems the app connects with the M300 but when I click the button "open" the app suddenly closes.

ADDITION: Additionally, I also tried the same steps for Rosetta drone "1" and it was impossible to load the code into the Smart Controller.

**Comment by The1only** [comment]
This is most lightly caused by video incompatibility. We seen this before, start by looking in the video handler.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by druzzo** [comment]
Thank you for your response. What do you mean by "video handler"?
Thank you
I was able to capture a video:
https://user-images.githubusercontent.com/85787053/171939669-87c15294-5bf7-4353-96f5-315433212284.mp4

**Comment by Phillweston** [comment]
DJI M300 needs DJI MSDK V5, which isn't supported by rosettadrone yet. So far the code is only compatible to 4.16.
I'll be glad if rosettadrone can compatible with DJI MSDK V5

**Comment by druzzo** [comment]
Ok Thank you very much for clarifying it. I will keep trying.
I also tested Rosetta in Phantom 4 RTK, and it does not work, it does not even connect.

**Comment by karikolehmainen** [comment]
DJI SSDK 4.16 release notes say that M300 RTK is supported. v5.0 adds support for M30...

**Comment by RocketRider** [comment]
It looks to me more like an Android error. I had a very similar issue with the Mavic 2 Enterprise and a Android 12 device.
You can try my fork if it is resolved there: https://github.com/RocketRider/rosettadrone

**Comment by kikislater** [comment]
@RocketRider Thank you, your version is working on /e/OS : Ungooglised android version

**Comment by kripper** [comment]
@RocketRider please submit a pull request to master branch or let us know what you changed.
