### ISSUE TITLE
Waypoint Action like Camera TAKE_PHOTO not working

### ISSUE THREAD

**Issue by Phillweston** [The1only/rosettadrone#113]
**Describe the bug**
When using waypoint actions like taking photos in waypoint, an error occurs after uploading the mission plan:

**To Reproduce**
1. Click on 'Fly'
2. Add 'Takeoff' point
3. Add 'Waypoint' with camera action like Take photo
4. Add 'RTL'
5. Upload mission
6. See error

**Expected behavior**
Waypoint uploaded and ready to execute.

**Screenshots**
APP
![image](https://user-images.githubusercontent.com/42629755/172672850-e27d4718-6187-4b1b-8614-ccaf5d0b18da.png)
QGC
![image](https://user-images.githubusercontent.com/42629755/172672892-0c2718a2-ec45-426a-a575-fe3178c543ec.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QGC: Version 4.2.1

**Smartphone (please complete the following information):**
 - Device: DJI Mavic 2 Pro with smart controller
 - DJI SDK Version: DJI SDK 4.16 

**Additional context**
Please help me with this problem, thanks!

**Comment by Phillweston** [comment]
In my mission above, the total distance is only 76m, far less than 500m. I think this is a bug related to the waypoint mission handling.

**Comment by kripper** [comment]
You can also try the new MissionManager (must be enabled in the code, search for "useMissionManager")

**Comment by kripper** [comment]
Let me know if you need help.
