### ISSUE TITLE
DJI Air 2S stream support

### ISSUE THREAD

**Issue by alyukovnet** [The1only/rosettadrone#117]
**Is your feature request related to a problem? Please describe.**
Application works with DJI Air 2S, but there isn't any video stream on smartphone and PC.

**Describe the solution you'd like**
To enable video stream I added string to switch in method `validateTranscodingMethod` in class `MainActivity`
```java
case DJI_AIR_2S:
```

Also I changed string in class `MainActivity`:
```java
mIsTranscodedVideoFeedNeeded = isTranscodedVideoFeedNeeded();
```
to
```java
mIsTranscodedVideoFeedNeeded = !isTranscodedVideoFeedNeeded();
```

**Comment by kripper** [comment]
Please check latest version. Video is a little tricky sometimes. Please try many times checking **only on your smartphone**, not on QGC.
