### ISSUE TITLE
In numerous places the project is titled "Rosetta Drone 3", while in other places the title is "Rosetta Drone 2"

### ISSUE THREAD

**Issue by gabehowe** [The1only/rosettadrone#127]
The title at the top of the README.MD file is "Welcome to Rosetta Drone 3", while the starting page on the app displays "Rosetta Drone 2". This problem is present in numerous other places as well.

**Comment by kripper** [comment]
Yes, we are looking for a better name without a number in it.
We will probably just use the name "Rosetta Drone" in the future.

**Comment by The1only** [comment]
Yes we can remove the number. And rather use versioning.Best regardTerje Nilsen9Tek ASNorwayOn 15 Mar 2023, at 21:16, Christopher Pereira ***@***.***> wrote:﻿
Yes, we are looking for a better name without a number in it.
We will probably just use the name "Rosetta Drone" in the future.
