### ISSUE TITLE
Failed arming checks (DroneKit and MAVSDK) and take off not reaching altitude

### ISSUE THREAD

**Issue by Sasysan** [The1only/rosettadrone#136]
**Describe the bug**
Hi, i am trying to write a simple script that is a simple takeoff and go in a desired position but i am having some problem. I notice that with DroneKit and MAVSDK is not possible to arm and takeoff (also with qgorund when i try the command takeoff appear a pop-up that tell me that is not possible to arm the drone), while with pymavlink is possible to arm and takeoff. There is another problem when i set the height of takeoff for example 5 mt when i start the script the height is ignored and the drone go a the maxium RTL height that is set in the app.

**Comment by kripper** [comment]
See: https://github.com/mavlink/MAVSDK/issues/1990

Every implementation is doing different arming checks and Rosetta probably is not passing them.

Feel free to add more messages to Rosetta to improve compatibility with more MAVLink implementations.

For the RTL altitude, check in the DJI manual how RTL works.

**Comment by Sasysan** [comment]
The problem is not with the RTL, the problem is with the takeoff. When I send a takeoff message for example of 5 meters, the drone is armed and starts the takeoff but does not reach the desired height but reaches the maximum RTL height set in the rosetta app

**Comment by kripper** [comment]
Regarding takeoff altitude, I fixed it here when using the new `MissionManager` instead of the old `MissionControlClass`:
https://github.com/The1only/rosettadrone/blob/e2216afdb9bba99374976f6ec12673c2b4a8e4eb/app/src/main/java/sq/rogue/rosettadrone/DroneModel.java#L1924

`MissionManager` is probably disabled and has not been tested with you model, but can be enabled and give you much more control.

Please always test in the simulator first and send pull requests.

**Comment by Sasysan** [comment]
The problem was not with the `MissionManager` but with  [motion.mask.ignorePosZ](https://github.com/The1only/rosettadrone/blob/e2216afdb9bba99374976f6ec12673c2b4a8e4eb/app/src/main/java/sq/rogue/rosettadrone/DroneModel.java#L1969) = true; if you comment that line the drone will go to the desire altitude.

**Comment by kripper** [comment]
Ok, this is new code and it probably broke recently. I will check and fix very soon.
