### ISSUE TITLE
Dronekit, rosettadrone, and dji mini2

### ISSUE THREAD

**Issue by OMAHDrone** [The1only/rosettadrone#148]
Dear rosettadrone developers,
First of all , we would like to thank you for this great app and your help, time, and support for running the app and fixing the issues of FFmpeg and git lfs.
I have successfully built rosettadrone  app on my phone and connect it to my dji mini 2. On the phone app screen, l can nicely see the telemetry data and video feed. However, my problem starts when l stream telemetry data and video feed to my QGC software installed on my windows 7 laptop. The issue is :
- I can not stream the video feed to the QGC software. Sometimes, l see black or green or flickering screen.
- I can not take off or control the drone using the QGC software or the app
- I can only see the telemetry data and when l physically move the dji mini2 the QGC software gets updated.
I would like to know if l miss anything.
Do rosettadrone3  app support controlling dji min 2 using python dronekit scripts ? If yes, what l should do or what l still miss to make it work. This is because even with the app l can not control the dji mini 2 although l can see both the telemetry data and video feed.
Thank you very much for your help and time
My pleasure

**Comment by kripper** [comment]
Yes, you can control the mini with Python.
Please check the issues and discussions section to gain knowledge, especially my comments.

**Comment by OMAHDrone** [comment]
Thank you very much kripper for your quick reply. May l have links for these comments or issues to study. I tried to read through the issues but l got lost.
Thank you very much again for your valuable help, time, and support
My pleasure

**Comment by kripper** [comment]
Duplicated
