### ISSUE TITLE
Drone is not detected

### ISSUE THREAD

**Issue by kripper** [The1only/rosettadrone#152]
### Describe the bug

Drone is not detected.

Try:
- Close and restart the app (this helps most of the time).
- Reconnect the Drone
- Make sure you have closed all other apps
- Make sure you gave all permissions to RosettaDrone and 
- Make sure the Drone is not overheating (you must place a fan in front if you are not flying).
- Make sure have read this [important notes](https://docs.google.com/document/d/1wR56Mvd2OsT82kxMOD7f_3-c6yJGBtLaT8LuVrmC5wI/edit?usp=sharing).

If your version worked once for you, this means you will have to figure out yourself how to make it work again, and let us know how you did it work, so we can maybe fix it (comment).

**Comment by OMAHDrone** [comment]
Thank you very much kripper
I have downloaded the repository again
I can confirm now I can open the Drone mode from the first time and it works fine. I tried many times and it works great. So this problem is solved.
Thank you very much for your help
My pleasure

**Comment by kripper** [comment]
But nothing important changed in the code regarding this isse, so the problem is probably still there, so you will have to figure out yourself how to make it work again, and let us know how you did it work, so we can maybe fix it (comment).
