### ISSUE TITLE
Waypoint not working on Mini 2

### ISSUE THREAD

**Issue by marcomacchia99** [The1only/rosettadrone#162]
### Describe the bug

Hi!
I need to test the waypoint mission using a DJI Mini 2 drone. When I go to settings>waypoint this message is shown in a toast:

> Not support Waypoint2.0

What am I doing wrong? I know that DJI Mobile SDK 4.16.4 does not support waypoint navigation for Mini 2, but MissionManager should overcome this problem.
Thank you

### Smartphone

```Markdown
- Device: [Samsung Galaxy S23]
```

**Comment by kripper** [comment]
Right. Check the code and enable MissionManager for your model.

**Comment by kripper** [comment]
BTW, I didn't add support for MissionManager in the in-app waypoints viewer. This means, you can send waypoints using QGC, but not view nor edit them inside Rosetta.

Feel free to change the in-app waypoints viewer to support the MissionManager class (should be easy) and please send a pull request.
