### ISSUE TITLE
No DJI SDK connection to Drone (probably hardware problems)

### ISSUE THREAD

**Issue by landynmj** [The1only/rosettadrone#170]
### Describe the bug

I have built and installed rosettadrone, Once connected to my RC, I get an unknown aircraft error. The drone and aircraft buttons do become available, but pressing them does nothing.

### Steps To Reproduce

Start rosetta drone. 
Turn on drone and RC.
Plug in device.

### Screenshots

https://i.imgur.com/TdDK0WA.png

### Smartphone

```Markdown
- Device: Pixel 6 Pro
- OS: 13 (TQ2A.230405.003.E1)
```

**Comment by kripper** [comment]
Put a breakpoint and find out what is being detected by the SDK.

I'm assuming DJI's app works properly.

**Comment by landynmj** [comment]
Would be possible, however wireless debugging won't work for me making it impossible to debug while plugging in the RC

**Comment by kripper** [comment]
Why not?
Do you need help to connect ADB via WiFi?

See also:
https://docs.google.com/document/d/1wR56Mvd2OsT82kxMOD7f_3-c6yJGBtLaT8LuVrmC5wI/edit?usp=sharing

**Comment by landynmj** [comment]
I keep getting stuck on "Connecting to device" Then it goes "There was an error pairing the device"

**Comment by kripper** [comment]
Please attach screenshot.

**Comment by landynmj** [comment]
I have figured out how to get it connected, had to add platform tools to path. Where should i place the breakpoint?

**Comment by kripper** [comment]
Check the ConnectionActivity where the aircraft model is obtained using the SDK.

Check why you are getting this message.

**Comment by landynmj** [comment]
When the debugger is connected, resuming the program once it initially launches closes the activity.

**Comment by kripper** [comment]
Again. See:
https://docs.google.com/document/d/1wR56Mvd2OsT82kxMOD7f_3-c6yJGBtLaT8LuVrmC5wI/edit?usp=sharing

**Comment by landynmj** [comment]
![image](https://github.com/RosettaDrone/rosettadrone/assets/24623877/dc1f6c7e-9f4b-434b-bc16-432bfe0de1c8)

**Comment by landynmj** [comment]
I have a breakpoint on line 262 `if (realProduct.isConnected()) {`

**Comment by kripper** [comment]
Check what is being returned by the SDK calls

**Comment by landynmj** [comment]
it returns the realProduct of the BaseProduct type. It is shown above,

**Comment by landynmj** [comment]
now it is returning null

**Comment by kripper** [comment]
Try to find out where this "Uknown" is comming from.
Is your model supported by the DJI SDK?

**Comment by landynmj** [comment]
Yes, it is supported by dji sdk, and it says it is tested in rosetta readme, which is why I am confused

**Comment by davidan208** [comment]
hi @gam3rboy7,
When you first build rosettadrone, do you have to install any other programs beside Android Studio (such as Java SDK, Gradle or something like that...). I'm keep getting the error saying that it is Java imcompatible, and unable to make field.

Can you tell me what is your building environment before import rosetta drone in Android Studio, and are there anything else that is required.

Thank you

**Comment by kripper** [comment]
The user reported unpredictable results (sometimes it works, sometimes not). This could be a problem with his smartphone, cable or drone.

**Comment by landynmj** [comment]
Same exact issue on brand new Pixel 7 Pro

**Comment by RustedBones** [comment]
I'm facing the same issue. The aircraft is also a `DJI Mini 2 SE`.
The README states the device has been tested, however doubt it. It looks like the DJI mobile SDK does not support this device. see https://github.com/dji-sdk/Mobile-SDK-Android-V5/issues/200

**Comment by kripper** [comment]
![image](https://github.com/RosettaDrone/rosettadrone/assets/1479804/0187fdb7-21cd-4e1e-9c2a-c326124ce2d6)

**Comment by RustedBones** [comment]
Sorry, I linked the wrong issue: https://github.com/dji-sdk/Mobile-SDK-Android/issues/1211

**Comment by kripper** [comment]
> I'm facing the same issue. The aircraft is also a `DJI Mini 2 SE`. The README states the device has been tested, however doubt it. It looks like the DJI mobile SDK does not support this device. 

You are right. It's currently not support by any SDK, so I removed it from the README.

**Comment by kripper** [comment]
> Yes, it is supported by dji sdk [...]

What model were you using?
