### ISSUE TITLE
Problem building Rosetta Drone on Android Studio

### ISSUE THREAD

**Issue by davidan208** [The1only/rosettadrone#172]
Hi guys,
I'm following the setup instruction to build the rosetta drone for my DJI. I have initialized with git lfs install, generated key for Google Map API and DJI App and put it in the desired locations. But when I built on Android Studio 3.6.4 ( Gradle version 6.8.3), I encountered this 
![image](https://github.com/RosettaDrone/rosettadrone/assets/37769067/dc77986e-fb02-4b4f-b155-92c45d559103)
Can any one give me a guide to overcome this problem, thanks a lot.

**Comment by kripper** [comment]
Did you import the project using `File->New->Import Project` ?

**Comment by davidan208** [comment]
Hi @kripper 
Yes I have. I''ve tried many times but it ends up the same.

> Did you import the project using `File->New->Import Project` ?

**Comment by kripper** [comment]
Maybe something changed in the cloud.
Please send a PR if you find the problem.

**Comment by davidan208** [comment]
> Maybe something changed in the cloud. Please send a PR if you find the problem.

Thank you @kripper.
One question, when I install Android Studio, are there anything I should consider, or just doing as the recommend settings; and then just import this repository and build the apk without any additional steps (beside adding the keys.xml)

**Comment by kripper** [comment]
No. I believe the correct grade version is automatically downloaded and installed when you import and build the project.

**Comment by davidan208** [comment]
> No. I believe the correct grade version is automatically downloaded and installed when you import and build the project.

This is the most recent problem since I'm starting over again @kripper. 
![image](https://github.com/RosettaDrone/rosettadrone/assets/37769067/fda34af3-1682-4b82-9f8b-5d6522f8bca6)

Any change I should change other version of Android studio ? I'm very new so I don't do java pretty much.
Thank you

**Comment by jashshah999** [comment]
Hi. Yes you can change your Android SDK Version. Go to File > Project Structure and under this you should see Android SDK Version which must be set to 17.x for you now. Click on the drop down and change it to 15. Then build the APK and you should be good to go!

**Comment by davidan208** [comment]
@jashshah999 you're a life saver. Thanks a lot my brother

**Comment by kripper** [comment]
Did something change and should we update the README build instructions?

**Comment by davidan208** [comment]
well actually it is about the SDK version, retry with SDK version 15 will immidiately ask for retry to build in Android Studio, and than just wait until done, cool project anyway @kripper

**Comment by estevezb** [comment]
Hi, I am having the same issue but when i go to File > Project Structure i don't know where to find the Android SDK Version. 
![image](https://github.com/RosettaDrone/rosettadrone/assets/56987765/51784888-b25b-45a7-af3b-c75934f4b13c)
![image](https://github.com/RosettaDrone/rosettadrone/assets/56987765/b984b343-7e63-4b11-a9d9-a266823ae4f5)

Would it be possible to provide a screen shot of those fields and menu?

**Comment by jashshah999** [comment]
Yes now click on grade settings. SDK version is now in Gradle settings.
You'll see the options there. Just click on the last link in your second
screenshot.

**Comment by estevezb** [comment]
@jashshah999 . Please excuse my ignorance I am new to Android studio and Java. I clicked on the Gradle Settings link. Here is the new window. It is currently showing 17.02 which I expected based on your information. Do i download a new JDK version? You mentioned choosing 15 from this dropdown? If so, which one?, there are also multiple vendors listed but not sure that is relevant. Here is another screen shot to make sure i am on the same page: 
![image](https://github.com/RosettaDrone/rosettadrone/assets/56987765/bb950984-d459-47c4-94b9-cc8de3c99873)

**Comment by estevezb** [comment]
@jashshah999. NM. This worked!!! Thank you!!!

**Comment by estevezb** [comment]
FYI, to the team, Readme could include , the specific vendor needed is azul 15  Azul Zulu : 
![image](https://github.com/RosettaDrone/rosettadrone/assets/56987765/eb2614c1-d88c-43c5-831b-8d98d3186432)

**Comment by dentava** [comment]
Good morning, i reached the last step but it's not working for me. @estevezb when i build it returns a popup saying: Unable to find Gradle tasks to build: []. Build mode: ASSEMBLE. Tests: None. How did you solved?

**Comment by cybrengineer** [comment]
The position of gradle settings have now changed and can't access it via the SDK structure menu, instead you can find it using the following:
![image](https://github.com/RosettaDrone/rosettadrone/assets/55183934/b647e14e-5b72-4714-a324-d53c8011d3ce)  

![image](https://github.com/RosettaDrone/rosettadrone/assets/55183934/445273ea-9387-46c2-8ff9-206fe03b37d5)

**Comment by CAMIprojectsUNI** [comment]
I have encountered the same errors as previous users. I followed their steps and their help was useful up to a certain point... but I get this error when trying to Build->Make Project.
![general_problem](https://github.com/user-attachments/assets/69fd8bcc-41d2-409a-a4ba-184247067dc4)

**Comment by angel-ayala** [comment]
Apparently seems to be a version problem with a dependency from Mapbox v9 which by the way [is not supported anymore](https://github.com/mapbox/mapbox-maps-android/issues/2457#issuecomment-2293256647)., I don't know exactly if is still being served since it continues appearing in [maven's repo](https://mvnrepository.com/artifact/com.mapbox.mapboxsdk/mapbox-android-accounts/0.7.0)

UPDATE:
There is actually no file at https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/

**Comment by HEEJUN-SHIN** [comment]
Hello, @angel-ayala @CAMIprojectsUNI, the problem comes from  DJI UXSDK 4:16 and 
I found temporal solution from DJI Developer support.

https://sdk-forum.dji.net/hc/en-us/articles/37229365477657-During-the-compilation-of-the-MSDK-V5-example-where-it-stated-Could-not-find-com-mapbox-mapboxsdk-mapbox-android-accounts-0-7-0-How-should-address-this

you can add
```
 maven { url 'https://maven.aliyun.com/repository/public' }
 maven { url 'https://maven.aliyun.com/repository/google' }
 maven { url 'https://repo.huaweicloud.com/repository/maven'}
```

inside allprojects/repositories in project-level build.gradle.

**Comment by ricricricricric** [comment]
hi
i have this problem when trying to build. 

![Image](https://github.com/user-attachments/assets/520fc7b3-161b-4d4e-8721-7b1c5fe3ea15)

I tried my best to understand what is going on and spent a lot of time goggling but this is just a completely foreign language to me.  Sorry for the ignorance.

**Comment by angel-ayala** [comment]
@ricricricricric  I'm not sure about what the problem is, however, appears that you are working on a labeled sourced code, have you tried making a clone of the repo? or download the master branch?

**Comment by Reto80** [comment]
Hallo und Guten Tag, danke vielmals für Ihre Arbeit (RosettaDrone), jedoch scheitere ich am erstellen der App und brauche Ihre Hilfe Arbeite momentan mit Android Studio 2021.1.3.1 mit Azul Zulu 15.0.10 Android Gradle Plugin Version 3.6.4 und Gradle Version 7.5 natürlich habe ich die Key Datei mit DJI und Gogle Api Key erstellt. I need Help  from Your Smart Brain. Best Wishes from Swiss
