### ISSUE TITLE
Cannot build RosettaDrone dispite doing similar to the documentation

### ISSUE THREAD

**Issue by CaptMaverick2000** [The1only/rosettadrone#173]
![image](https://github.com/RosettaDrone/rosettadrone/assets/141800789/614c8082-16a1-4951-9961-b6b45d1c292e)
Hello, I'm doing this for a school project but can not build rosettaDrone on Android Studio? One thing is that I'm doing the default setup and it turns out like this. 

What should I do to build this, any recommendations about the OS, building environment,... will be very much appreciate.

Please help me, thank you.

**Comment by jashshah999** [comment]
Hi. Yes you can change your Android SDK Version. Go to File > Project Structure and under this you should see Android SDK Version which must be set to 17.x for you now. Click on the drop down and change it to 15. Then build the APK and you should be good to go!
