### ISSUE TITLE
Can't connect UDP port from Rosettadrone App to QGC or Dronekit using DJI Mavic Air 2

### ISSUE THREAD

**Issue by jpa4094** [The1only/rosettadrone#181]
### Describe the bug

I have successfully managed to install the app from Android Studio. And it is able to successfully configure the DJI SDK product key. I even did the configurations for using external device for GCS and inserted the telemetry config. However, when i try to connect to the drone from dronekit or QGC, it doesn't seem to connect. Could there be something else i missed out? Kindly help me please. 

### Drone Model

```Markdown
DJI Mavic Air 2
```

### Smartphone Model

```Markdown
- Model:OPPO
- Android version:12
```

**Comment by kripper** [comment]
What was the problem?

**Comment by jpa4094** [comment]
Once i used the same device to access rosettadrone, QGCS and Dronekit, the
UDP worked so no problem. Previously i used different devices that didn't
work.

However now i have a new issue. The drone is able to take off from dronekit
python script. But, no matter what altitute i set, the drone keeps hovering
at 1.2 metres only. I tried all functions that i can think of such as
channel override, rc_channel_raw, changing roll, pitch and throttle values
etc. However, the drone still stays there. Could you help me out in this? I
need to make the drone move left, right, forward, backward and upward.
Thanks in advance 🙏

**Comment by jpa4094** [comment]
Once i used the same device to access rosettadrone, QGCS and Dronekit, the UDP worked so no problem. Previously i used different devices that didn't work. 

However now i have a new issue. The drone is able to take off from dronekit python script. But, no matter what altitute i set, the drone keeps hovering at 1.2 metres only. I tried all functions that i can think of such as channel override, rc_channel_raw, changing roll, pitch and throttle values etc. However, the drone still stays there. Could you help me out in this? I need to make the drone move left, right, forward, backward and upward. Thanks in advance 🙏

**Comment by kripper** [comment]
Use a debugger to see the logs.

**Comment by jpa4094** [comment]
There is no error it seems. It ignores
 the commands given.

**Comment by jpa4094** [comment]
Received unknown message. This is what i see in the logs as u can see in the screenshot![image](https://github.com/RosettaDrone/rosettadrone/assets/64852996/b4f458e8-eb6d-4d31-8b5a-b5f5609fbefb)![image](https://github.com/RosettaDrone/rosettadrone/assets/64852996/ab16efc0-a32a-4d3b-add5-768388026e58)

**Comment by kripper** [comment]
Use Android Studio.
You can implement the important missing MAV messages looking at the other similar messages implementation.

Remember to check:
https://docs.google.com/document/d/1wR56Mvd2OsT82kxMOD7f_3-c6yJGBtLaT8LuVrmC5wI/edit#heading=h.pbfib4hdz684

**Comment by jpa4094** [comment]
Alright will look through. By the way, just to ask if Rosettadrone has to be connected to QGC at the same time as well in order for the python script to work?

**Comment by jpa4094** [comment]
I just saw the documentation and followed closely. It says received unknown message followed by MAV command. So do i need to edit the code on Android studio ?

**Comment by kripper** [comment]
Yes. You should Google what messages are being sent by your python script, find out which ones you really need and implement them by looking how other messages are implemented.

You can also adapt your python script to use other messages 

Welcome aboard and have fun.

**Comment by kripper** [comment]
> Alright will look through. By the way, just to ask if Rosettadrone has to be connected to QGC at the same time as well in order for the python script to work?

QGC is not needed, but could be useful to monitor your drone.

**Comment by jpa4094** [comment]
Thank you so much sir! You solved my issue that I have been troubleshooting for past 4 days. Yes I would implement vision algorithms as well and will definitely contribute as well!

**Comment by kripper** [comment]
What did you do? Use other mavlink messages in your python script? In this case, which MAVLink msg was not working and which one worked?

**Comment by jpa4094** [comment]
Sorry for late reply. Well, I tried with Mavlink commands like mavutil.mavlink.MAVLink_rc_channels_raw_message() didn't work. After trying 
def send_local_ned_velocity(vx, vy, vz):
    msg = vehicle.message_factory.set_position_target_local_ned_encode(
        0,
        0, 0,
        mavutil.mavlink.MAV_FRAME_BODY_OFFSET_NED,
        0b0000111111000111,
        0, 0, 0,
        vx, vy, vz,
        0, 0, 0,
        0, 0)
worked! I got this from one of the discussions that i read from this repository. 
Thanks.

**Comment by jpa4094** [comment]
Btw, referring to the Hacking Rosetta document, to enable video stream from Rosetta to Dronekit, do we compulsory need linux version ? Does Windows don't support it ?

**Comment by kripper** [comment]
The raw video streamer should work fine on any platform.

BTW, someone reported that RTP streaming was working fine with QGC for Linux, but not for Windows.
This should be investigated further.

**Comment by jpa4094** [comment]
Alright i followed ediitng the PluginManager.java file and changing the hardcoded hostname to my PC ip address where i want the video to be streamed on. But when i go to the web browser on my pc and key in the ip address that i specified : 6000, the video still cannot stream.

**Comment by kripper** [comment]
You didn't read the section "Receiving the Images directly in Python"

**Comment by kripper** [comment]
And you hallucinated that your browser is capable of receiving this custom format that contains the drone's yaw :-)

Your next comment will probably be about the latency:

If you notice high latency, check the fps your are sending and the fps you are receiving. If you are sending too much frames per second, they will stack on the receiving end and produce latency. Check the code. It's quite simple.

**Comment by jpa4094** [comment]
Yes exactly you read my mind well :) I am reading your live editing on the document as well as reading other issues as well. Thanks

**Comment by jpa4094** [comment]
I changed the number of frames from 15 to 6 to 3 and then to 1 currently since it has to be a divisor of 30. But i think now is slightly better with a delay of 2-3 seconds only.

**Comment by jpa4094** [comment]
Btw Changing the code to improve video latency do u mean in Android Studio or Python script ?

**Comment by kripper** [comment]
In both I guess.

**Comment by jpa4094** [comment]
I have been trying to modify the Android Studio code to create a link between the Telemetry 3 host input and the host address hardcoded in the RawvideoStreamer file. I have tried intent method but it seems not working. Is there any method u would recommend me to use ?

**Comment by kripper** [comment]
Telemetry ports and RawVideoStreamer ports are two completely different things and should not be linked.

**Comment by jpa4094** [comment]
Alright, I have managed to create a new text input to add in and update the IP Host address and port of the raw video streamer from the app itself instead pf constantly updating the script and building it each and every time I use it at various locations.

**Comment by jpa4094** [comment]
However, would like to check whether to run the vision landing and smart landing scripts, is it compulsory to use Linux and not Windows?

**Comment by kripper** [comment]
I only developed and tested on Linux.
Please note the code to track the targets is written in C++.
