### ISSUE TITLE
Do you know if it's possible to control attitude (roll, pitch, yaw)? I tried code from dronekit examples (https://github.com/dronekit/dronekit-python/blob/master/examples/set_attitude_target/set_attitude_target.py), but it does't work, nothing changes

### ISSUE THREAD

**Issue by jpa4094** [The1only/rosettadrone#183]
Do you know if it's possible to control attitude (roll, pitch, yaw)? I tried code from dronekit examples (https://github.com/dronekit/dronekit-python/blob/master/examples/set_attitude_target/set_attitude_target.py), but it does't work, nothing changes

_Originally posted by @paw-krz in https://github.com/RosettaDrone/rosettadrone/issues/36#issuecomment-1404377051_

**Comment by kripper** [comment]
Yes. Please use Android Studio to debug the problem with your script.
