### ISSUE TITLE
Drone keeps hovering on 1 metre for DJI Mavic Air 2 regardless of any other commands like simple_goto

### ISSUE THREAD

**Issue by jpa4094** [The1only/rosettadrone#184]
Dear Dronekit friends,

I've successfully connect Rosetta Drone and Dronekit, and use python script to interact with my Drone (Mavic Mini). It works with `simple_takeoff` command, but the altitude of my drone is stuck at 1 m although I set a higher altitude. Other command like `simple_goto` also not working, my drone doesn't move anywhere.

Any idea how to solve this issue? Thanks.

_Originally posted by @fajrulfx in https://github.com/RosettaDrone/rosettadrone/issues/36#issuecomment-878754085_

**Comment by kylenietfeld** [comment]
Same issue here except it stays at the same altitude previously. Is it because DJI requires at least two points for a waypoint mission? Anyone have a working example?

**Comment by kripper** [comment]
Check the logcat.
It seems your drone is executing the take-off command and then stops executing other commands.

**Comment by czarekk215** [comment]
@jpa4094 Did you manage to solve the problem?
