### ISSUE TITLE
DJI Mini 2 No Takeoff with QGC

### ISSUE THREAD

**Issue by stw2nf** [The1only/rosettadrone#189]
### Describe the bug

I have a Mini 2 connected to a Smart Controller running Rosetta Drone. I can successfully connect to the vehicle via UDP to QGroundControl, and open a vehicle connection Dronekit-python. A simple_takeoff command in Dronekit gets no response, and a takeoff command via QGC yields the error "Unable to takeoff. Vehicle failed to arm". Additionally any efforts to send velocity commands via Dronekit-python after manually arming and taking off don't produce any movement. The one command that does seem to work from both QGC and Dronekit is changing to Land mode.

Appreciate any advice! This is a great project and I am excited to utilize it.

### Screenshots

![image](https://github.com/RosettaDrone/rosettadrone/assets/57158922/5d151dd2-4af0-414b-86c6-904785d99a21)

### Drone Model

```Markdown
DJI Mini 2
```

### Smartphone Model

```Markdown
- Model: DJI Smart Controller
- Android version: 7.1.2
```

**Comment by stw2nf** [comment]
RTL seems to crash RosettaDrone app as well.

**Comment by The1only** [comment]
And you armed Rosettadrone to allow for takeoff, and selected the  correct mavlink protocol i QGC?Best regardTerje Nilsen9Tek ASNorwayOn 1 Nov 2023, at 14:50, stw2nf ***@***.***> wrote:﻿
Describe the bug
I have a Mini 2 connected to a Smart Controller running Rosetta Drone. I can successfully connect to the vehicle via UDP to QGroundControl, and open a vehicle connection Dronekit-python. A simple_takeoff command in Dronekit gets no response, and a takeoff command via QGC yields the error "Unable to takeoff. Vehicle failed to arm". Additionally any efforts to send velocity commands via Dronekit-python after manually arming and taking off don't produce any movement. The one command that does seem to work from both QGC and Dronekit is changing to Land mode.
Appreciate any advice! This is a great project and I am excited to utilize it.
Steps To Reproduce
No response
Screenshots

Drone Model
DJI Mini 2
Smartphone Model
- Model: DJI Smart Controller
- Android version: 7.1.2
Additional context
No response

**Comment by stw2nf** [comment]
@The1only I have unlocked the safety through Rosetta Drone. 

The mavlink protocol I am unsure about. Does this refer to when first booting QGC selecting the flight stack firmware you will be using, ArduPilot or PX4? In that case I believe I selected ArduPilot, but I will double check that is the case. Here are my Mavlink Settings through Application Settings on QGC though, and I just unchecked "Only accept MAVs with the same protocol version"

![image](https://github.com/RosettaDrone/rosettadrone/assets/57158922/6474f8f4-7766-4326-86a7-ecafdaa70d58)

**Comment by stw2nf** [comment]
@The1only So I did a reinstall of QGC and on that opening selection picked "Mavlink Generic. Have that "Only accept MAVs with the same protocol version" unchecked as well but still seeing the same behavior. 

Not sure if that was in line with what you were thinking the problem may be.

Thanks so much for the help! I really appreciate it.

**Comment by stw2nf** [comment]
Similar to Issue #186 the buttons on the left side of RosettaDrone app are greyed out, I am receiving 100% loss rate in Mavlink messages and no video through QGC (Video streams fine through Mission Planner)

**Comment by kylenietfeld** [comment]
I have same issue with Mavic 2 Pro. Not sure if I have some settings that are wrong. Readme and Hacking Rosetta Drone Guide don't have lots of information on QGC settings and makes me think it should work with default settings.

Takeoff and Land commands work with my Mini from QGC. QGC does not connect to the video stream though.

**Comment by stw2nf** [comment]
@kylenietfeld Were there any changes that you made that allowed for takeoff? Are you building off master branch?

**Comment by kylenietfeld** [comment]
@stw2nf I didn't do anything special. I just followed the instructions in the readme. I built the app, specified the IP address, connected to QGC, unlocked, and the takeoff/land worked. However, the same procedure is not working for my Mavic 2 Pro and I am not sure why

**Comment by stw2nf** [comment]
@kylenietfeld In testing this I had a recent development. In C mode (Tripod in RosettaDrone) and S mode (Sport in RosettaDrone) if I give the vehicle a takeoff command, I get the same error "Vehicle failed to arm". However, if I then send a land command through QGC and then rapidly send another takeoff command as soon as possible through QGC the vehicle will arm and takeoff. I can't replicate this in N mode (P-GPS in RosettaDrone) though. I wonder if this sequence would work on your Mavic 2 as well? I am going to test on my Mini 2 from Dronekit-Python as well

**Comment by kripper** [comment]
I remember take off from QGC used to fail the first time giving a "failed to arm" error. Setting to "auto" and retrying was the workaround I used.
I believe it was a problem with the checks performed by QGC.

In your case, you reported "100% loss rate in Mavlink messages".
Maybe a firewall blocking your UDP packets?
Make sure QGC is receiving messages sent by RosettaDrone.

BTW, You don't need to change anything related with MAVLink protocol version in QGC. I implemented V2 in RosettaDrone.

**Comment by kripper** [comment]
I created: https://github.com/RosettaDrone/rosettadrone/issues/191

**Comment by stw2nf** [comment]
@kripper Thanks a ton. In the flurry of debugging either I ended up doing what you recommended and arming in Auto mode accidently, or that Takeoff -> Land -> Takeoff sequence is another workaround for the Mini 2 /QGC combination. Regardless, after the first time, everything has been operating as expected. This is a fantastic project and hope to contribute where I am capable moving forward! Thanks for the help!

**Comment by juand5678** [comment]
@stw2nf  Before taking off, does the video stream work for you in the QGC? I couldn't connect the video, could you help me? this is my email diego.aristizabal@udea.edu.co

**Comment by kripper** [comment]
> @stw2nf Before taking off, does the video stream work for you in the QGC? I couldn't connect the video, could you help me? this is my email [diego.aristizabal@udea.edu.co](mailto:diego.aristizabal@udea.edu.co)

See https://github.com/RosettaDrone/rosettadrone/issues/175
