### ISSUE TITLE
Error while running 'app'. Default activity not found

### ISSUE THREAD

**Issue by KroSmi** [The1only/rosettadrone#195]
### Describe the bug

Hello.
After building the app succefully, for some reason i can't run the app on the emulator and it give me this message : 
![image](https://github.com/RosettaDrone/rosettadrone/assets/149018172/768342a2-7219-4de3-ad72-b9642b3cb7eb)
![image](https://github.com/RosettaDrone/rosettadrone/assets/149018172/360a2659-30ee-4157-b286-b20798942dc3)

Do i have to run the app for rosetta to start or should i run an other file ? 
![image](https://github.com/RosettaDrone/rosettadrone/assets/149018172/ff42f922-6cbe-44d7-9c10-b7809b5f07a7)

### Drone Model

```Markdown
Dji air 2s
```

### Smartphone Model

```Markdown
- Model: Pixel 3a
- Android version: 14
```

**Comment by CunningLogic** [comment]
post your manifest, or tthe resulting APK if it builds

**Comment by KroSmi** [comment]
This is the androidmanifest.xml From C\user\AndroidStudioProjects\Test\app\src\main.
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="sq.rogue.rosettadrone.test" >

    <uses-sdk
        android:minSdkVersion="26"
        android:targetSdkVersion="34" />

    <instrumentation
        android:name="androidx.test.runner.AndroidJUnitRunner"
        android:functionalTest="false"
        android:handleProfiling="false"
        android:label="Tests for sq.rogue.rosettadrone"
        android:targetPackage="sq.rogue.rosettadrone" />

    <uses-permission android:name="android.permission.REORDER_TASKS" />

    <queries>
        <package android:name="androidx.test.orchestrator" />
        <package android:name="androidx.test.services" />
        <package android:name="com.google.android.apps.common.testing.services" />
    </queries>

    <application
        android:debuggable="true"
        android:extractNativeLibs="false" >
        <uses-library android:name="android.test.runner" />

        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity"
            android:exported="true"
            android:theme="@style/WhiteBackgroundTheme" >
            <intent-filter android:priority="-100" >
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyActivity"
            android:exported="true"
            android:theme="@style/WhiteBackgroundTheme" >
            <intent-filter android:priority="-100" >
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="androidx.test.core.app.InstrumentationActivityInvoker$EmptyFloatingActivity"
            android:exported="true"
            android:theme="@style/WhiteBackgroundDialogTheme" >
            <intent-filter android:priority="-100" >
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>`

I can't attach you the .apk file but i tried installing the apk on my android phone and it did not open!

**Comment by KroSmi** [comment]
Btw the way i am new to android studio so sorry if i do things the wrong way

**Comment by KroSmi** [comment]
the problem seems to be fixed by itself and the problems now are these :
![image](https://github.com/RosettaDrone/rosettadrone/assets/149018172/b352e309-429c-4dd3-b343-f8dd744d754e)
![image](https://github.com/RosettaDrone/rosettadrone/assets/149018172/04b935ae-3a5c-41df-93eb-64e47d8856df)
![image](https://github.com/RosettaDrone/rosettadrone/assets/149018172/7667e86f-ed48-41d1-8971-05ec7baa2184)

**Comment by KroSmi** [comment]
i found the answer on issue #55  
and this message specificaly helped alot:
![image](https://github.com/RosettaDrone/rosettadrone/assets/149018172/e5640099-062f-4f2e-b5ef-fab35b549a28)
