### ISSUE TITLE
MAVLink data collection

### ISSUE THREAD

**Issue by joshMeise** [The1only/rosettadrone#213]
Hello,
I am working on a project which requires me to extract MAVLink messages between a DJI drone and GCS. I have successfully been able to simulate drone flights in jMAVSim and collect MAVLink messages. Would using RosettaDrone alongside QGroundControl allow for me to collect a dataset containing MAVLink messages from a DJI drone?

**Comment by kripper** [comment]
I believe QGC has an option to record mavlink messages.
MavProxy too.

Why do you want to record the messages?

**Comment by joshMeise** [comment]
Thank you. I am doing an analysis of the messages for a project and need to obtain a few datasets for the analysis.
