### ISSUE TITLE
recently added webrtc code breaks build

### ISSUE THREAD

**Issue by tednv** [The1only/rosettadrone#223]
### Describe the bug

```
rosettadrone\app\src\main\java\sq\rogue\rosettadrone\plugins\WebRTCStreaming.java:60: error: m_model is not public in DroneModel; cannot be accessed from outside package
            if (pluginManager.mainActivity.mModel.m_model == null) {
                                                 ^
rosettadrone\app\src\main\java\sq\rogue\rosettadrone\plugins\WebRTCStreaming.java:68: error: m_model is not public in DroneModel; cannot be accessed from outside package
                        pluginManager.mainActivity.mModel.m_model, stunServer);
                                                         ^
```

### Steps To Reproduce

Checkout master, build

### Drone Model

```Markdown
mavic 2 pro
```

### Smartphone Model

```Markdown
- Model:
- Android version:
```

### Additional context

tried several different gradle and java versions to see if it's a compatibility issue, all fail consistently with the same error

**Comment by kripper** [comment]
Just make it public?

@angel-ayala maybe some required changes were not included in the pull request?

**Comment by tednv** [comment]
tried making public, which does get apk release to build but then when running on phone it crashes as soon as video feed begins so there are probably other things that were missing from the pr

**Comment by kripper** [comment]
Take a look at the android logcat logs.
See: https://github.com/RosettaDrone/rosettadrone?tab=readme-ov-file

**Comment by angel-ayala** [comment]
Oh yes, I forgot to update `DroneModel` class, as I did some other changes to use with the P4P I did not push those changes, I will make the  changes in my repo and then the PR

**Comment by tednv** [comment]
awesome, works now, thank you for quick fix!
