### ISSUE TITLE
Can't build due to linking failure: FAILED: libdjivideojni.so

### ISSUE THREAD

**Issue by tr0043t** [The1only/rosettadrone#92]
Builds (on all platforms) are failing at linkage with:

FAILED: libdjivideojni.so

I've seen this discussed in some other rosettadrone forks but the solutions seem nebulous at best and not clear what the best solution is for this fork. Any ideas? Does anyone have a working apk (with the current Mini 2 support) available for testing? Thanks very much!

**Comment by ghost** [comment]
Make sure you use `git lfs` installed in your system and clone it using the commands:
```
git lfs install 
GIT_SSL_NO_VERIFY=1 https://github.com/The1only/rosettadrone.git
```

**Comment by The1only** [comment]
This is a very common problem, I should print it out loud somewhere.!  Suggestions?

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by ghost** [comment]
Yes, I think you should add it in the README.md. 

Thanks & Regards
Himanshu V
Vyorius Drones Pvt Ltd
India
