### ISSUE TITLE
Help to connect drone to python program

### ISSUE THREAD

**Issue by kumar-rajwnai** [The1only/rosettadrone#96]
I have seen dji tello but i want to use DJI Mavic series.

https://diydrones.com/profiles/blogs/dji-drone-controlled-by-ai-python-script

I want to create this thing. I have no idea about how to connect drone to my python application. Can you give me an overview of how to get frames from the drone in my python application and control drone?

Is there any article which teach this things from scratch then please also share the link of it.

**Comment by BkMak16** [comment]
Is it possible, yes.

Is there an article or tutorial, no.

What you're referring to is my contribution to this and we're still working on it. It might take some time.

Welcome to the Think Tank.

**Comment by The1only** [comment]
There are examples in this Q&A in some stream.

Best regard
Terje Nilsen
9Tek AS
Norway

**Comment by kripper** [comment]
See https://github.com/RosettaDrone/rosettadrone/discussions/133
